name: Build jellyfin nightly

on:
  workflow_dispatch:
  schedule:
    - cron: 30 0 * * *

jobs:
  Docker-trigger-scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
        
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'nightly'
      - run: |
          dt=`date +%Y%m%d%H%M%S`
          echo $dt
          sed -i "7c LABEL build_version=\"sleepgod version:nightly Build-date:$dt\"" Dockerfile
          git config user.name sleepgod
          git config user.email dingwenxuan@gmail.com
          git add .
          git commit -m "build_version"
          git push
